import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartDrawer from '@/components/CartDrawer'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 1. Ajoute le Header ici pour qu'il soit disponible partout */}
        <Header />
        {/* 2. Ajoute le CartDrawer ici pour qu'il soit disponible partout */}
        <CartDrawer />
        {children}
        {/* 3. Ajoute le Footer ici pour qu'il soit disponible partout */}
        <Footer />
      </body>
    </html>
  );
}
